### PR TITLE
Fix synchronization

### PR DESCRIPTION
**Pull request by SebastienMichoy**
The synchronization was broken due to changes on https://apple.github.io/swift-evolution/. This PR fixes these changes.

#### Modified:
- URL used to fetch proposals
- Parsing (JSON instead of XML)
- Some information in view models (e.g. Proposals identifiers include `SE-`, they are not only number anymore)

#### Added:
- SwiftyJSON library (via Pods)
- New proposal status (`.acceptedWithRevisions `)

#### Removed:
- SWXMLHash library (from Pods)

### CODE REVIEW

**Comment by lypiut** [comment]
Pods in the repo don't make the PR very readable 👎

**Comment by SebastienMichoy** [comment]
@lypiut I'm pretty mixed about this., but in general, I think it's a good thing because you're sure to don't have problem with decencies (e.g. a pod is removed). It also allows people who don't have *cocoapods* to be able to launch the project.

**Comment by Neirys** [comment]
@SebastienMichoy Build failed :)

**Comment by SebastienMichoy** [comment]
As explained in 5ecebafbc72a463bda95b92afa8681e91ae10ce6, the status `.implementing` doesn't appear in the file `index.js` of https://apple.github.io/swift-evolution/.

```javascript
var states = {
  '.awaitingReview': {
    name: 'Awaiting Review',
    shortName: 'Awaiting Review',
    className: 'awaiting-review'
  },
  '.scheduledForReview': {
    name: 'Scheduled for Review',
    shortName: 'Scheduled',
    className: 'scheduled-for-review'
  },
  '.activeReview': {
    name: 'Active Review',
    shortName: 'Active Review',
    className: 'active-review'
  },
  '.returnedForRevision': {
    name: 'Returned for Revision',
    shortName: 'Returned',
    className: 'returned-for-revision'
  },
  '.withdrawn': {
    name: 'Withdrawn',
    shortName: 'Withdrawn',
    className: 'withdrawn'
  },
  '.deferred': {
    name: 'Deferred',
    shortName: 'Deferred',
    className: 'deferred'
  },
  '.accepted': {
    name: 'Accepted',
    shortName: 'Accepted',
    className: 'accepted'
  },
  '.acceptedWithRevisions': {
    name: 'Accepted with revisions',
    shortName: 'Accepted',
    className: 'accepted-with-revisions'
  },
  '.rejected': {
    name: 'Rejected',
    shortName: 'Rejected',
    className: 'rejected'
  },
  '.implemented': {
    name: 'Implemented',
    shortName: 'Implemented',
    className: 'implemented'
  },
  '.error': {
    name: 'Error',
    shortName: 'Error',
    className: 'error'
  }
}
```

What're your thoughts about it? Should `.implementing` be removed?

**Comment by SebastienMichoy** [comment]
***[Updated version of the Pull Request]***

The synchronization was broken due to changes on https://apple.github.io/swift-evolution/. This PR fixes these changes.

#### Modified:
- URL used to fetch proposals
- Parsing (JSON instead of XML)
- Some information in view models (e.g. Proposals identifiers include `SE-`, they are not only number anymore)

#### Added:
- New proposal status (`.acceptedWithRevisions`)

#### Removed:
- SWXMLHash library (from Pods)

**Comment by Neirys** [comment]
Maybe @lypiut can take a look at that one (i'm short in time)

**Comment by lypiut** [comment]
@SebastienMichoy rebase you branch and I will check :)

**Review by lypiut — APPROVED** [review]
In order to fix the CI add the following code in `.travis.yml`
```
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec pod install --repo-update
```

**Comment by SebastienMichoy** [comment]
Don't really understand why CI cannot fetch the pods, but I updated `.travis.yml` with @lypiut's code. It should fix the issue.

**Comment by lypiut** [comment]
Because cocoapod's repo is not up to date and cannot find the latest version of the library

**Comment by SebastienMichoy** [comment]
Make sense.

**Pull request merged**
